# jdbc.X
jdbc.driverClassName=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/snowman?createDatabaseIfNotExist=true&serverTimezone=UTC
jdbc.username=snowuser
jdbc.password=snowpass

# hibernate.X
hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
hibernate.show_sql=true
# validate | update | create | create-drop
hibernate.hbm2ddl.auto=validate

# Messaging - JMS
jms.brokerUrl=tcp://localhost:61616
